# Generated by Django 4.2 on 2026-07-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('stripe', 'Stripe (Card)'), ('chapa', 'Chapa')], max_length=15),
        ),
    ]
