# Generated by Django 4.2 on 2026-07-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='charged_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('usd', 'US Dollar'), ('etb', 'Ethiopian Birr')], default='usd', max_length=3),
        ),
    ]
