services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ethio_tour_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ethio_tour_frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

networks:
  default:
    name: ethio_tour_network
