# Generated by Django 6.0.6 on 2026-07-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('overview', models.TextField()),
                ('category', models.CharField(choices=[('adventure', 'Adventure'), ('luxury', 'Luxury'), ('family', 'Family'), ('wildlife', 'Wildlife'), ('historical', 'Historical'), ('trekking', 'Trekking'), ('birdwatch', 'Bird Watching')], default='adventure', max_length=20)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_discount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('duration_nights', models.PositiveSmallIntegerField()),
                ('max_group_size', models.PositiveSmallIntegerField(default=12)),
                ('min_group_size', models.PositiveSmallIntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('extreme', 'Extreme')], default='moderate', max_length=10)),
                ('languages', models.CharField(default='English', max_length=200)),
                ('transportation', models.TextField(blank=True)),
                ('accommodation', models.TextField(blank=True)),
                ('meals', models.CharField(blank=True, max_length=100)),
                ('inclusions', models.TextField(blank=True)),
                ('exclusions', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='packages/covers/')),
                ('video_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinations', models.ManyToManyField(blank=True, related_name='packages', to='destinations.destination')),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages.tourpackage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_seats', models.PositiveSmallIntegerField()),
                ('booked_seats', models.PositiveSmallIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='packages.tourpackage')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meals', models.CharField(blank=True, max_length=100)),
                ('accommodation', models.CharField(blank=True, max_length=200)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='packages.tourpackage')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('package', 'day_number')},
            },
        ),
    ]
