# Generated by Django 5.2.16 on 2026-07-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='accommodation_am',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='accommodation_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='accommodation_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_am',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='meals_am',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='meals_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='meals_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_am',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='accommodation_am',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='accommodation_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='accommodation_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='exclusions_am',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='exclusions_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='exclusions_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='inclusions_am',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='inclusions_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='inclusions_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meals_am',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meals_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meals_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='overview_am',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='overview_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='overview_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tagline_am',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tagline_fr',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='title_am',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='transportation_am',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='transportation_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='transportation_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
