# Generated by Django 5.2.16 on 2026-07-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_itineraryday_accommodation_am_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageimage',
            name='caption_am',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packageimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packageimage',
            name='caption_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meta_description_am',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meta_title_am',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meta_title_fr',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
