# Generated by Django 5.2.16 on 2026-07-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_packageimage_caption_am_packageimage_caption_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='meta_description_am',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='meta_title_am',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='meta_title_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
