# Generated by Django 5.2.16 on 2026-07-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_tourpackage_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='meals',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='meals_am',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='meals_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='meals_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
