# Generated by Django 5.2.16 on 2026-07-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_meta_description_am_post_meta_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_am',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_am',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_fr',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
