# Generated by Django 5.2.16 on 2026-07-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_best_time_am_destination_best_time_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyattraction',
            name='description_am',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nearbyattraction',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nearbyattraction',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nearbyattraction',
            name='name_am',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearbyattraction',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nearbyattraction',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
