# Generated by Django 5.2.16 on 2026-07-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_nearbyattraction_description_am_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='altitude_m_am',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='altitude_m_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='altitude_m_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='altitude_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
